export const SET_SHIPPING_FAIL = "SET_SHIPPING_FAIL";
export const SET_SHIPPING = "SET_SHIPPING";
export const SET_CONFIRMATION = "SET_CONFIRMATION"
export const SET_CONFIRMATION_FAIL = "SET_CONFIRMATION_FAIL"

